stages:
  - debug
  - format-check
  - build
  - test

spotless-check:
  image: openjdk:17-jdk
  stage: format-check
  script:
    - ./gradlew clean spotlessCheck
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
