stages:
  - format-check
  - build
  - test

spotless-check:
  stage: format-check
  script:
    - ./gradlew spotlessCheck
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
