stages:
  - format-check
  - test

variables:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configuration-cache=false"

spotless-check:
  image: openjdk:17-jdk
  stage: format-check
  script:
    - ./gradlew clean spotlessCheck
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  image: openjdk:17-jdk
  stage: test
  script:
    - ./gradlew clean testDevDebugUnitTest --no-daemon