stages:
  - debug
  - format-check
  - build
  - test

debug-environment:
  stage: debug
  script:
    - echo "=== Operating System Info ==="
    - uname -a
    - cat /etc/os-release
    - echo "=== Java Installation Check ==="
    - java -version || echo "Java not found in PATH"
    - javac -version || echo "Javac not found in PATH"
    - echo "=== Available Java Installations ==="
    - ls -la /usr/lib/jvm/ || echo "No JVM directory found"
    - echo "=== Environment Variables ==="
    - echo $JAVA_HOME
    - echo $PATH
    - echo "=== Which Java ==="
    - which java || echo "Java executable not found"
    - which javac || echo "Javac executable not found"


spotless-check:
  stage: format-check
  script:
    - ./gradlew spotlessCheck
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
