stages:
  - format-check
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configuration-cache=false"

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

spotless-check:
  image: inovex/gitlab-ci-android
  stage: format-check
  script:
    - ./gradlew clean spotlessCheck
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  image: inovex/gitlab-ci-android
  stage: test
  script:
    - ./gradlew clean testDebugUnitTest --no-daemon
