stages:
  - debug
  - format-check
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

spotless-check:
  image: openjdk:17-jdk
  stage: format-check
  script:
    - echo "Java version:"
    - java -version
    - echo "Running Spotless check..."
    - ./gradlew spotlessCheck
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
